<?php

namespace App\Models;

enum TeacherClass
{
    const PROFESSIONAL_PREPARATION = 'PROFESSIONAL_PREPARATION';
    const PHYSICAL_EDUCATION = 'PHYSICAL_EDUCATION';
    const NATURAL_SCIENCES = 'NATURAL_SCIENCES';
    const MATHEMATICS_INFORMATICS = 'MATHEMATICS_INFORMATICS';
    const BG_LANGUAGE_LITERATURE = 'BG_LANGUAGE_LITERATURE';
    const FOREIGN_LANGUAGES = 'FOREIGN_LANGUAGES';
    const SOCIAL_SCIENCES = 'SOCIAL_SCIENCES';
    const TEACHER_STAFF = 'TEACHER_STAFF';
}
